### ISSUE TITLE
Run command remotely via ssh method in utils

### ISSUE THREAD

**Issue by dhodovsk** [user-cont/conu#176]
It might be handy to have a utils method that would:
 - open a connection to a remote machine via ssh
 - run command/set of commands on it

**Comment by TomasTomecek** [comment]
I would love if we clearly defined the use case for this. @jscotka (because I can't remember it any more :D)

**Comment by jscotka** [comment]
this case is to invoke commands in same way with various backends.
means, that now execute method, will wrap commands with some magic around that
for nspawn it is much more difficult, because of stdout/stderr inside systemd units. so in case there will be some ssh, or another service like telnet what will do that, it will run commands in these env in same way,

**Comment by SkullTech** [comment]
We can use [`fabric`](https://github.com/fabric/fabric) for this purpose. It's very popular, so _maybe_ it's robust framework. Should I take a shot making this function using `fabric`?

**Comment by TomasTomecek** [comment]
I would not spend time to work on code for this issue since it is still not clear. We should first have a design, which should be then approved. After that I would start with an implementation.

@jscotka made the use case more clear, but personally I wonder whether we actually still need this.

@SkullTech if you are looking for some more work, https://github.com/user-cont/conu/issues/24 this one would be awesome to have. We are pleased for receiving great contributions of yours, but out of curiosity, what's your motivation?

**Comment by SkullTech** [comment]
Thanks for your feedback! @TomasTomecek 

Well as for my motivation, I'll be completely honest. Let me first make my situation clear — 

- I'm an undergrad CS student, currently in third year.
- I'm a big fan of open-source and Python. 
- I have started to get into the world of infrastructures recently, like sysadmin stuffs, devops, containerization, cloud and those sorts of things. I know I'm being __very__ broad here, but to be honest I haven't really focused on a particular topic as of yet.
- So naturally I was looking for projects to contribute to where my interests may come together, and then I came upon `user-cont` projects, through _GSOC 2018_ project ideas.
- Also I might say, seeing my interests you may have already guessed that I'm a big fan of RedHat too, as it advocates open-source and open infrastructure. So `user-cont` being a part of RedHat was a welcome surprise for me. 
- So given all the above, I naturally got interested in these `user-cont` projects. I'm also hoping to start working in some larger related projects as I gain some familiarity with all these. I'm excited to get into the RedHat // Fedora // GNOME world! 

I know you maybe were not looking for a wall of text xD, but I thought it would be best to share my situation with you, so that you along with the rest of @user-cont team can guide me.

**Comment by dhodovsk** [comment]
We decided that it is not important for now.
